/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Conexion;
import Clases.Operaciones;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Partes Gonzalez
 */
public class Principal extends javax.swing.JFrame {

    Connection con;
    Operaciones op;
    Conexion cn;
    int seleccion, modificacion, stock, cambioss;
    public Object[][] dtRef;
    private DefaultTableModel datosRef;

    /**
     * Creates new form Principal
     */
    public Principal(String User) {

        cn = new Conexion();
        cn.AccederBD();
        initComponents();
        ocultarventacompra();
        if ("Usuario".equals(User)) {
            usuariosM.setEnabled(false);
            actividadM.setEnabled(false);
        }
        this.setExtendedState(MAXIMIZED_BOTH);
        datosRef = new DefaultTableModel();
        cn = new Conexion();
        op = new Operaciones();
        this.setLocationRelativeTo(null);
        Tabla.setModel(datosRef);
        con = cn.AccederBD();
        actuTablaCli();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcMousePanel1 = new jcMousePanel.jcMousePanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        btCompra = new org.edisoncor.gui.button.ButtonAction();
        txtCAN = new org.edisoncor.gui.textField.TextFieldRound();
        btBuscar = new org.edisoncor.gui.button.ButtonAction();
        labelRound1a = new org.edisoncor.gui.label.LabelRound();
        btTodos1 = new org.edisoncor.gui.button.ButtonAction();
        labelRound2 = new org.edisoncor.gui.label.LabelRound();
        labelRound1a1 = new org.edisoncor.gui.label.LabelRound();
        txtBuscar1 = new org.edisoncor.gui.textField.TextFieldRound();
        txtID1 = new org.edisoncor.gui.textField.TextFieldRound();
        btAceptar = new org.edisoncor.gui.button.ButtonColoredAction();
        btCancelar = new org.edisoncor.gui.button.ButtonColoredAction();
        btVen = new org.edisoncor.gui.button.ButtonAction();
        jMenuBar1 = new javax.swing.JMenuBar();
        actividadM = new javax.swing.JMenu();
        refacciones = new javax.swing.JMenuItem();
        usuariosM = new javax.swing.JMenu();
        administrarusers = new javax.swing.JMenuItem();
        sistema = new javax.swing.JMenu();
        acerca = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Partes Gonzalez");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/actividades.png")).getImage());

        jcMousePanel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo.jpg"))); // NOI18N
        jcMousePanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea2.setBackground(new java.awt.Color(255, 204, 102));
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jcMousePanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 490, 560));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 102));
        jLabel1.setText("Notas del dia");
        jcMousePanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 350, -1));

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setResizable(false);
            Tabla.getColumnModel().getColumn(1).setResizable(false);
            Tabla.getColumnModel().getColumn(2).setResizable(false);
            Tabla.getColumnModel().getColumn(3).setResizable(false);
        }

        jcMousePanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 190, 620, 100));

        btCompra.setText("Compra");
        btCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCompraActionPerformed(evt);
            }
        });
        jcMousePanel1.add(btCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 300, 130, 40));
        jcMousePanel1.add(txtCAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 160, 30));

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });
        jcMousePanel1.add(btBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 110, 130, 40));

        labelRound1a.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground"));
        labelRound1a.setText("CANTIDAD");
        labelRound1a.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jcMousePanel1.add(labelRound1a, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 430, 190, 30));

        btTodos1.setText("Mostrar Todos");
        btTodos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTodos1ActionPerformed(evt);
            }
        });
        jcMousePanel1.add(btTodos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, 130, 40));

        labelRound2.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground"));
        labelRound2.setText("Inventario");
        labelRound2.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jcMousePanel1.add(labelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 40, 600, 50));

        labelRound1a1.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledForeground"));
        labelRound1a1.setText("ID");
        labelRound1a1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jcMousePanel1.add(labelRound1a1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 190, 30));

        txtBuscar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscar1ActionPerformed(evt);
            }
        });
        jcMousePanel1.add(txtBuscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 110, 250, 40));
        jcMousePanel1.add(txtID1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, 160, 30));

        btAceptar.setBackground(new java.awt.Color(0, 204, 0));
        btAceptar.setText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });
        jcMousePanel1.add(btAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 370, 150, -1));

        btCancelar.setBackground(new java.awt.Color(204, 0, 0));
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        jcMousePanel1.add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 430, 150, -1));

        btVen.setText("Venta");
        btVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVenActionPerformed(evt);
            }
        });
        jcMousePanel1.add(btVen, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 130, 40));

        actividadM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actividades2.png"))); // NOI18N
        actividadM.setText("Refacciones");

        refacciones.setText("Refacciones");
        refacciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refaccionesActionPerformed(evt);
            }
        });
        actividadM.add(refacciones);

        jMenuBar1.add(actividadM);

        usuariosM.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/usuarios.png"))); // NOI18N
        usuariosM.setText("Usuarios");

        administrarusers.setText("Administrar Usuarios");
        administrarusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administrarusersActionPerformed(evt);
            }
        });
        usuariosM.add(administrarusers);

        jMenuBar1.add(usuariosM);

        sistema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sistema.png"))); // NOI18N
        sistema.setText("Sistema");

        acerca.setText("Acerca de...");
        acerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaActionPerformed(evt);
            }
        });
        sistema.add(acerca);

        jMenuBar1.add(sistema);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1360, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jcMousePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refaccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refaccionesActionPerformed
        Refacciones rf = new Refacciones(this, true);
        rf.setVisible(true);
    }//GEN-LAST:event_refaccionesActionPerformed

    private void administrarusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administrarusersActionPerformed
        Usuarios users = new Usuarios(this, true);
        users.setVisible(true);
    }//GEN-LAST:event_administrarusersActionPerformed

    private void btCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCompraActionPerformed
        int fila = Tabla.getSelectedRow();
        if (fila >= 0) {
            txtID1.setText(Tabla.getValueAt(fila, 0).toString());
            activarcompraventa();
            seleccion = 2;
        } else {
            JOptionPane.showMessageDialog(this, "No se selecciono ninguna fila", "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btCompraActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        Buscar(txtBuscar1.getText());
    }//GEN-LAST:event_btBuscarActionPerformed

    private void acercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaActionPerformed
        JOptionPane.showMessageDialog(this, "Elaborado por: \nJair Ignacio Gonzalez Gayosso \nCarlos Alfonso Tonatiuh Nochebuena Olvera \nSergio Donaldo Lira Gebara", "Acerca de....", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_acercaActionPerformed

    private void btTodos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTodos1ActionPerformed
        actuTablaCli();
    }//GEN-LAST:event_btTodos1ActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        if (seleccion == 1) {

            int malsn = 0;
            
                
                

                String sql;
                sql = "SELECT * FROM Refacciones WHERE id='" + txtID1.getText() + "'";
                
                try {
                    PreparedStatement pst = con.prepareStatement(sql);
                    ResultSet rs = pst.executeQuery();
                    while (rs.next()) {
                        
                        String mals = rs.getString(2);
                        malsn=Integer.parseInt(mals);
                        
                        }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                stock = malsn;
                String cs = txtCAN.getText();
                cambioss = Integer.parseInt(cs);
                System.out.println(cambioss);
                if (cambioss<=stock) {
                    venta(stock, cambioss);
                } else {
                    JOptionPane.showMessageDialog(this, "No se cuenta con la cantidad suficiente", "Error", JOptionPane.ERROR_MESSAGE);
                    
                }

            ocultarventacompra();

        }
        if (seleccion == 2) {
            
            
            int malsn = 0;
            
                
                

                String sql;
                sql = "SELECT * FROM Refacciones WHERE id='" + txtID1.getText() + "'";
                
                try {
                    PreparedStatement pst = con.prepareStatement(sql);
                    ResultSet rs = pst.executeQuery();
                    while (rs.next()) {
                        
                        String mals = rs.getString(2);
                        malsn=Integer.parseInt(mals);
                        
                        }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
                stock = malsn;
                String cs = txtCAN.getText();
                cambioss = Integer.parseInt(cs);
                System.out.println(cambioss);
                if (cambioss > 0) {
                    compra(stock, cambioss);
                } else {
                    JOptionPane.showMessageDialog(this, "No se puede comprar 0 articulos", "Error", JOptionPane.ERROR_MESSAGE);
                    
                }

            
            ocultarventacompra();
            
        }

    }//GEN-LAST:event_btAceptarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        ocultarventacompra();

    }//GEN-LAST:event_btCancelarActionPerformed

    private void btVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVenActionPerformed
        int fila = Tabla.getSelectedRow();
        if (fila >= 0) {
            txtID1.setText(Tabla.getValueAt(fila, 0).toString());
            activarcompraventa();
            seleccion = 1;
        } else {
            JOptionPane.showMessageDialog(this, "No se selecciono ninguna fila", "Error", JOptionPane.ERROR_MESSAGE);

        }
         
    }//GEN-LAST:event_btVenActionPerformed

    private void txtBuscar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JMenuItem acerca;
    private javax.swing.JMenu actividadM;
    private javax.swing.JMenuItem administrarusers;
    private org.edisoncor.gui.button.ButtonColoredAction btAceptar;
    private org.edisoncor.gui.button.ButtonAction btBuscar;
    private org.edisoncor.gui.button.ButtonColoredAction btCancelar;
    private org.edisoncor.gui.button.ButtonAction btCompra;
    private org.edisoncor.gui.button.ButtonAction btTodos1;
    private org.edisoncor.gui.button.ButtonAction btVen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea2;
    private jcMousePanel.jcMousePanel jcMousePanel1;
    private org.edisoncor.gui.label.LabelRound labelRound1a;
    private org.edisoncor.gui.label.LabelRound labelRound1a1;
    private org.edisoncor.gui.label.LabelRound labelRound2;
    private javax.swing.JMenuItem refacciones;
    private javax.swing.JMenu sistema;
    private org.edisoncor.gui.textField.TextFieldRound txtBuscar1;
    private org.edisoncor.gui.textField.TextFieldRound txtCAN;
    private org.edisoncor.gui.textField.TextFieldRound txtID1;
    private javax.swing.JMenu usuariosM;
    // End of variables declaration//GEN-END:variables

    public void actuTablaCli() {
        String[] columNames = {"ID", "CANTIDAD", "DESCRIPCION", "PRECIO"};
        // se utiliza la funcion
        dtRef = op.getRefacciones(con);

        // se colocan los datos en la tabla
        datosRef = new DefaultTableModel(dtRef, columNames);
        Tabla.setModel(datosRef);

    }

    private void Buscar(String valor) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("CANTIDAD");
        modelo.addColumn("DESCRIPCION");
        modelo.addColumn("PRECIO");
        Tabla.setModel(modelo);
        String sql;
        sql = "SELECT * FROM Refacciones WHERE id='" + valor + "'";
        String[] datos = new String[4];
        try {
            PreparedStatement pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                datos[0] = rs.getString(1);
                datos[1] = rs.getString(2);
                datos[2] = rs.getString(3);
                datos[3] = rs.getString(4);
                modelo.addRow(datos);
            }
            Tabla.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void compra(int valor1, int valor2) {
        int modif = valor1 + valor2;
        String ese = String.valueOf(modif);
        String q = "UPDATE Refacciones SET cantidad='" + ese + "' WHERE id='" + txtID1.getText() + "'";
        try {
            PreparedStatement pst = con.prepareStatement(q);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Compra Registrada");
            actuTablaCli();
            ocultarventacompra();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void venta(int valor1, int valor2) {
        int modif = valor1 - valor2;
        String ese = String.valueOf(modif);
        String q = "UPDATE Refacciones SET cantidad='" + ese + "' WHERE id='" + txtID1.getText() + "'";
        try {
            PreparedStatement pst = con.prepareStatement(q);
            pst.execute();
            JOptionPane.showMessageDialog(this, "Venta Registrada");
            actuTablaCli();
            ocultarventacompra();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void ocultarventacompra() {
        txtCAN.setEnabled(false);
        txtID1.setEnabled(false);
        btAceptar.setEnabled(false);
        btCancelar.setEnabled(false);
        txtCAN.setVisible(false);
        txtID1.setVisible(false);
        btAceptar.setVisible(false);
        btCancelar.setVisible(false);
        txtCAN.setText("");
        txtID1.setText("");
        txtID1.setEditable(false);
    }

    private void activarcompraventa() {
        txtCAN.setEnabled(true);
        txtID1.setEnabled(true);
        btAceptar.setEnabled(true);
        btCancelar.setEnabled(true);
        txtCAN.setVisible(true);
        txtID1.setVisible(true);
        btAceptar.setVisible(true);
        btCancelar.setVisible(true);
    }
}
